%% Hexagram 38
graph LR

    %% Nodes
    ctx-self([context-self])
    ctx-pred([context-pred])
    ctx-succ([context-succ])
    core[bit-nand]
    final[bit-or]
    output([output-sigil])
    style output stroke:#333,stroke-width:3px

    %% Edges
    ctx-self -->|a| core
    ctx-succ -->|b| core
    core -->|result → a| final
    ctx-pred -->|b| final
    final -->|result → sigil| output