;;; -*- lexical-binding: t -*-
;;; Held-out mechanism test for the original MetaCA propagator harness.

(require 'cl-lib)
(require 'run)

(defconst mechanism-neighbourhoods
  ["000" "001" "010" "100" "011" "101" "110" "111"])

(defconst mechanism-mirror [0 3 2 1 6 5 4 7])

(defconst mechanism-cases
  ;; Predictions were fixed before any held-out run.  P predicts life iff at
  ;; most three edges preserve neighbourhood Hamming weight and 000/111 are
  ;; in different permutation orbits.
  '((:name "rotate+2-anchor" :perm [2 3 4 5 6 7 0 1]
     :held-out nil :prediction live)
    (:name "two-4-cycles-anchor" :perm [1 2 3 0 5 6 7 4]
     :held-out nil :prediction dead)
    (:name "3+5-cycles-anchor" :perm [1 2 0 4 5 6 7 3]
     :held-out nil :prediction live)
    (:name "flip-left" :perm [3 5 6 0 7 1 2 4]
     :held-out t :prediction live)
    (:name "flip-centre" :perm [2 4 0 6 1 7 3 5]
     :held-out t :prediction live)
    (:name "flip-right" :perm [1 0 4 5 2 3 7 6]
     :held-out t :prediction live)
    (:name "left-right-mirror" :perm [0 3 2 1 6 5 4 7]
     :held-out t :prediction dead)
    (:name "complement-neighbourhood" :perm [7 6 5 4 3 2 1 0]
     :held-out t :prediction dead)
    (:name "rotate-neighbourhood-left" :perm [0 2 3 1 6 4 5 7]
     :held-out t :prediction dead)
    (:name "rotate-neighbourhood-right" :perm [0 3 1 2 5 6 4 7]
     :held-out t :prediction dead)
    (:name "centre-xor-left" :perm [0 1 2 6 4 7 3 5]
     :held-out t :prediction dead)
    (:name "centre-xor-right" :perm [0 4 2 3 1 7 6 5]
     :held-out t :prediction dead)
    (:name "right-xor-left" :perm [0 1 2 5 4 3 7 6]
     :held-out t :prediction dead)))

(defun mechanism-weight (bits)
  (cl-count ?1 bits))

(defun mechanism-hamming-distance (a b)
  (cl-loop for k below 3
           count (/= (aref a k) (aref b k))))

(defun mechanism-distance-histogram (perm)
  (let ((distances
         (cl-loop for k below 8
                  collect (mechanism-hamming-distance
                           (aref mechanism-neighbourhoods k)
                           (aref mechanism-neighbourhoods (aref perm k))))))
    (cl-loop for distance from 0 to 3
             collect (cl-count distance distances))))

(defun mechanism-weight-preserving-edges (perm)
  (cl-loop for k below 8
           count (= (mechanism-weight (aref mechanism-neighbourhoods k))
                    (mechanism-weight
                     (aref mechanism-neighbourhoods (aref perm k))))))

(defun mechanism-same-orbit-p (perm a b)
  (let ((cursor a) (seen nil) (found nil))
    (while (and (not found) (not (memq cursor seen)))
      (if (= cursor b)
          (setq found t)
        (push cursor seen)
        (setq cursor (aref perm cursor))))
    found))

(defun mechanism-property-p (perm)
  (and (<= (mechanism-weight-preserving-edges perm) 3)
       (not (mechanism-same-orbit-p perm 0 7))))

(defun mechanism-commutes-with-mirror-p (perm)
  (cl-loop for k below 8
           always (= (aref mechanism-mirror (aref perm k))
                     (aref perm (aref mechanism-mirror k)))))

(defun mechanism-random-byte ()
  (apply #'string
         (cl-loop repeat 8 collect (if (= 0 (random 2)) ?0 ?1))))

(defun mechanism-isolated-finals (name perm)
  (let (finals)
    (dotimes (seed 32)
      (random (format "mechanism-isolated-%s-%d" name seed))
      (let ((rule (mechanism-random-byte))
            (prop (make-perm-prop perm)))
        (dotimes (_ 400)
          (setq rule (funcall prop rule nil)))
        (cl-pushnew rule finals :test #'string=)))
    (sort finals #'string<)))

(defun mechanism-run-case (case)
  (let* ((name (plist-get case :name))
         (perm (plist-get case :perm))
         (runs (cl-loop for seed below 4
                        collect (run-propagator perm seed 60 120))))
    (append case
            (list :property (mechanism-property-p perm)
                  :weight-preserving
                  (mechanism-weight-preserving-edges perm)
                  :distance-histogram (mechanism-distance-histogram perm)
                  :extremes-same-orbit
                  (mechanism-same-orbit-p perm 0 7)
                  :commutes-with-mirror
                  (mechanism-commutes-with-mirror-p perm)
                  :deaths (mapcar (lambda (r) (plist-get r :death)) runs)
                  :rules (mapcar (lambda (r) (plist-get r :rules)) runs)
                  :activities (mapcar (lambda (r) (plist-get r :activity)) runs)
                  :isolated-finals (mechanism-isolated-finals name perm)))))

(defun mechanism-main ()
  (let ((output (or (getenv "MECHANISM_OUT")
                    "data/propagator-mechanism-results.el"))
        (results (mapcar #'mechanism-run-case mechanism-cases)))
    (with-temp-file output
      (insert ";; Generated by scripts/propagator_mechanism.el\n")
      (pp results (current-buffer)))
    (princ (format "wrote %s (%d cases)\n" output (length results)))))

(mechanism-main)
