;;; propagator_search_worker.el --- Batch worker for propagator search -*- lexical-binding: t -*-

;; This file deliberately contains no dynamics.  `run-propagator', loaded from
;; scripts/elisp-harness/run.el, is the authority: it executes the unedited 2014
;; MetaCA source.  This worker only turns task descriptions into atomic EDN
;; artefacts, one per (permutation, seed).

(require 'cl-lib)

(defun propagator-search--vector-edn (xs)
  (format "[%s]" (mapconcat #'number-to-string (append xs nil) " ")))

(defun propagator-search--strings-edn (xs)
  (format "[%s]" (mapconcat (lambda (x) (prin1-to-string x)) xs " ")))

(defun propagator-search--write-result (task result)
  (let* ((path (plist-get task :path))
         (dir (file-name-directory path))
         (tmp nil)
         (perm (plist-get task :perm))
         (seed (plist-get task :seed))
         (fingerprint (plist-get task :fingerprint))
         (width (plist-get task :width))
         (steps (plist-get task :steps)))
    (make-directory dir t)
    (setq tmp (make-temp-file (expand-file-name ".partial-" dir)))
    (unwind-protect
        (progn
          (with-temp-file tmp
            (insert
             (format (concat "{:status :complete :fingerprint %S "
                             ":perm %s :seed %d "
                             ":protocol {:width %d :steps %d :invert true} "
                             ":measured {:death %d :rules %d :activity %d "
                             ":phe %s}}\n")
                     fingerprint
                     (propagator-search--vector-edn perm)
                     seed width steps
                     (plist-get result :death)
                     (plist-get result :rules)
                     (plist-get result :activity)
                     (propagator-search--strings-edn
                      (plist-get result :phe)))))
          (rename-file tmp path t)
          (setq tmp nil))
      (when (and tmp (file-exists-p tmp)) (delete-file tmp)))))

(defun propagator-search-run-batch (task-file)
  "Run every task in TASK-FILE through the authoritative harness.

TASK-FILE is Emacs-readable data generated by propagator_search.clj.  Completed
artefacts are selected and validated by the Clojure driver before they reach
this worker; each result is written atomically so an interrupted batch loses at
most its current run."
  (let ((tasks (with-temp-buffer
                 (insert-file-contents task-file)
                 (goto-char (point-min))
                 (read (current-buffer))))
        (done 0))
    (dolist (task tasks)
      (let ((result (run-propagator (plist-get task :perm)
                                    (plist-get task :seed)
                                    (plist-get task :width)
                                    (plist-get task :steps))))
        (propagator-search--write-result task result)
        (setq done (1+ done))
        (when (= 0 (% done 20))
          (princ (format "completed %d/%d\n" done (length tasks))))))
    (princ (format "completed %d/%d\n" done (length tasks)))))

(provide 'propagator-search-worker)
;;; propagator_search_worker.el ends here
