;; Compatibility shim for 2014-era elisp: Emacs 30 removed the old `cl` package.
;; Aliases only — the legacy source is not edited, so what runs IS the original.
(require 'cl-lib)
(defalias 'map 'cl-map)
(defalias 'mapcar* 'cl-mapcar)
(defalias 'first 'cl-first)
(defalias 'second 'cl-second)
(defalias 'third 'cl-third)
(defalias 'member-if 'cl-member-if)
(defalias 'remove-if 'cl-remove-if)
(defalias 'remove-if-not 'cl-remove-if-not)
(defalias 'find-if 'cl-find-if)
(defalias 'position 'cl-position)
(defalias 'rotatef 'cl-rotatef)
(defalias 'incf 'cl-incf)
(defalias 'decf 'cl-decf)
(defalias 'loop 'cl-loop)
(defalias 'case 'cl-case)
(unless (fboundp 'string-to-int) (defalias 'string-to-int 'string-to-number))
(provide 'clcompat)
